"""Provision and verify the tmux side of continuation-over-reboot.

`bin/periscope install` already wires periscope's half (the pane-session hook
and the launchd job) but continuation also needs TPM + tmux-resurrect +
tmux-continuum installed and a handful of tmux options set — most critically
`@resurrect-hook-post-save-layout` pointing at THIS checkout's
`bin/periscope resurrect-rewrite`. Left to hand configuration, the hook path
rots when the checkout moves and a fresh machine silently never saves
(`resurrect.save_now` degrades quietly when continuum is absent).

Periscope owns a sourced file, `<config_dir>/tmux.conf`, regenerated wholesale
on every install, and adds exactly one `source-file` line to `~/.tmux.conf`.
TPM scans sourced files for `@plugin` lines, so the plugin list lives in the
owned file too. The source line must precede TPM's `run` line — TPM only
installs plugins declared before it runs — so it is inserted directly above an
existing `run ... tpm/tpm`, or appended together with one.

Import discipline: stdlib + `periscope.config` only. The shell verb runs this
under plain `python3`, outside the uv environment.
"""
import json
import os
import re
import shlex
import subprocess
import sys
import time
from pathlib import Path

from periscope import config

TPM_REPO = "https://github.com/tmux-plugins/tpm"
REQUIRED_PLUGINS = ("tpm", "tmux-resurrect", "tmux-continuum")
TPM_RUN_LINE = "run '~/.tmux/plugins/tpm/tpm'"
_DEFAULT_SAVE_INTERVAL_MIN = 15

_TPM_RUN_RE = re.compile(r"^\s*run(-shell)?\b.*tpm/tpm")
_SOURCE_RE = re.compile(
    r"^\s*source(-file)?\s+(-q+\s+)?['\"]?(?P<path>[^'\"\s]+)"
)


def plugins_dir() -> Path:
    return Path.home() / ".tmux/plugins"


def user_conf() -> Path:
    return Path.home() / ".tmux.conf"


def owned_conf() -> Path:
    return config.config_dir() / "tmux.conf"


def hook_command(repo: Path) -> str:
    return f"{repo}/bin/periscope resurrect-rewrite"


def source_line() -> str:
    return f"source-file {shlex.quote(str(owned_conf()))}"


def owned_conf_text(repo: Path) -> str:
    return (
        "# Generated by `bin/periscope install` — regenerated on every install/update.\n"
        "# The minimum tmux-resurrect/continuum setup for Claude panes to resume\n"
        "# their session after a reboot. Personal settings belong in ~/.tmux.conf.\n"
        "set -g @plugin 'tmux-plugins/tpm'\n"
        "set -g @plugin 'tmux-plugins/tmux-resurrect'\n"
        "set -g @plugin 'tmux-plugins/tmux-continuum'\n"
        "set -g @continuum-restore 'on'\n"
        "set -g @resurrect-processes '~claude'\n"
        f"set -g @resurrect-hook-post-save-layout {shlex.quote(hook_command(repo))}\n"
    )


# --- ~/.tmux.conf line management -----------------------------------------

def _sources_owned(line: str) -> bool:
    m = _SOURCE_RE.match(line)
    return bool(m) and Path(os.path.expanduser(m.group("path"))) == owned_conf()


def _read_lines(path: Path) -> list[str]:
    return path.read_text().splitlines() if path.exists() else []


def _write_lines(path: Path, lines: list[str]) -> None:
    path.write_text("\n".join(lines) + "\n")


def is_sourced(path: Path) -> bool:
    return any(_sources_owned(line) for line in _read_lines(path))


def ensure_sourced(path: Path) -> bool:
    """Add the source line to `path` per the ordering rule. True if written."""
    lines = _read_lines(path)
    if any(_sources_owned(line) for line in lines):
        return False
    tpm_at = next((i for i, line in enumerate(lines) if _TPM_RUN_RE.match(line)), None)
    if tpm_at is None:
        lines += [source_line(), TPM_RUN_LINE]
    else:
        lines.insert(tpm_at, source_line())
    _write_lines(path, lines)
    return True


def remove_sourced(path: Path) -> bool:
    """Drop the source line from `path`. True if written."""
    lines = _read_lines(path)
    kept = [line for line in lines if not _sources_owned(line)]
    if len(kept) == len(lines):
        return False
    _write_lines(path, kept)
    return True


# --- install / uninstall ----------------------------------------------------

def _tmux_server_running() -> bool:
    try:
        return subprocess.run(
            ["tmux", "list-sessions"], capture_output=True, check=False,
        ).returncode == 0
    except OSError:
        return False


def install(repo: Path) -> list[str]:
    """Provision everything; returns the actions taken, for the verb to print.
    Raises on a failure that leaves continuation broken."""
    actions: list[str] = []
    conf = owned_conf()
    conf.parent.mkdir(parents=True, exist_ok=True)
    text = owned_conf_text(repo)
    if not conf.exists() or conf.read_text() != text:
        conf.write_text(text)
        actions.append(f"wrote {conf}")
    if ensure_sourced(user_conf()):
        actions.append(f"added source line to {user_conf()}")

    tpm = plugins_dir() / "tpm"
    if not tpm.is_dir():
        tpm.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            ["git", "clone", "--depth", "1", TPM_REPO, str(tpm)],
            check=True, capture_output=True, text=True,
            env={**os.environ, "GIT_TERMINAL_PROMPT": "0"},
        )
        actions.append(f"cloned tpm into {tpm}")
    # TPM reports a failed clone only as text, never via exit code — verify the
    # directories ourselves.
    subprocess.run([str(tpm / "bin/install_plugins")], check=True, capture_output=True)
    missing = [p for p in REQUIRED_PLUGINS if not (plugins_dir() / p).is_dir()]
    if missing:
        raise RuntimeError(f"tpm failed to install: {', '.join(missing)}")
    actions.append("tmux plugins present: " + ", ".join(REQUIRED_PLUGINS))

    if _tmux_server_running():
        subprocess.run(
            ["tmux", "source-file", str(user_conf())],
            check=True, capture_output=True, text=True,
        )
        actions.append("re-sourced ~/.tmux.conf on the running server")
    return actions


def uninstall() -> list[str]:
    actions: list[str] = []
    if remove_sourced(user_conf()):
        actions.append(f"removed source line from {user_conf()}")
    conf = owned_conf()
    if conf.exists():
        conf.unlink()
        actions.append(f"removed {conf}")
    return actions


# --- status (healthz) ---------------------------------------------------------

def _live_option(name: str) -> str | None:
    """Value of a global tmux option on the running server; None when there
    is no server. `-q` makes an unset option print empty rather than error."""
    try:
        out = subprocess.run(
            ["tmux", "show-options", "-gqv", name],
            capture_output=True, text=True, check=False, timeout=2.0,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if out.returncode != 0:
        return None
    return out.stdout.rstrip("\n")


def _resurrect_dir(live_override: str | None) -> Path:
    # Mirrors tmux-resurrect's own resolution order (scripts/helpers.sh).
    if live_override:
        return Path(os.path.expanduser(live_override))
    legacy = Path.home() / ".tmux/resurrect"
    if legacy.is_dir():
        return legacy
    base = os.environ.get("XDG_DATA_HOME") or os.path.expanduser("~/.local/share")
    return Path(base) / "tmux/resurrect"


def status(repo: Path) -> dict:
    plugins = {p: (plugins_dir() / p).is_dir() for p in REQUIRED_PLUGINS}
    conf_sourced = is_sourced(user_conf())

    restore = _live_option("@continuum-restore")
    live = restore is not None
    processes = (_live_option("@resurrect-processes") or "") if live else ""
    hook = (_live_option("@resurrect-hook-post-save-layout") or "") if live else ""
    interval_raw = _live_option("@continuum-save-interval") if live else None
    try:
        interval_min = int(interval_raw) if interval_raw else _DEFAULT_SAVE_INTERVAL_MIN
    except ValueError:
        interval_min = _DEFAULT_SAVE_INTERVAL_MIN

    last = _resurrect_dir(_live_option("@resurrect-dir") if live else None) / "last"
    last_save_at: int | None = None
    if last.exists():
        last_save_at = int(last.stat().st_mtime)
    stale = last_save_at is not None and time.time() - last_save_at > 2 * interval_min * 60

    checks = {
        "restore_on": restore == "on",
        "processes_ok": "~claude" in processes.split(),
        "hook_current": os.path.expanduser(hook) == hook_command(repo),
    }
    return {
        "ok": all(plugins.values()) and conf_sourced and all(checks.values()) and not stale,
        "plugins": plugins,
        "conf_sourced": conf_sourced,
        **checks,
        "last_save_at": last_save_at,
        "last_save_stale": stale,
    }


def main(argv: list[str]) -> int:
    verb = argv[0] if argv else ""
    if verb == "install" and len(argv) == 2:
        for a in install(Path(argv[1]).resolve()):
            print(a)
        return 0
    if verb == "uninstall":
        for a in uninstall():
            print(a)
        return 0
    if verb == "status" and len(argv) == 2:
        print(json.dumps(status(Path(argv[1]).resolve()), indent=2))
        return 0
    print("usage: python -m periscope.tmux_persist {install <repo>|uninstall|status <repo>}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
